
export const RecipeImage = {
  EspressoShot: "espressoShot.jpg",
  WhiteChocolateMocha: "whiteChocolateMocha.jpg",
  MochaPump: "mochaPump.jpg",
  WhippedCreamDispenser: "whippedCreamDispenser.jpg",
  StirSpoon: "stirSpoon.jpg",
  MilkPitcher: "milkPitcher.jpg",
  WholeMilkPitcher: "wholeMilkPitcher.jpg",
  AlmondMilkPitcher: "almondMilkPitcher.jpg",
  Pumpkin: "pumpkin.jpg",
  Peppermint: "peppermint.jpg",
  ToastedWhiteChocolateMocha: "toastedWhiteChocolateMocha.jpg",
  CaramelBrulee: "caramelBrulee.jpg",
  SugarCookie: "sugarCookie.jpg",
  PumpkinSpicePowder: "pumpkinSpicePowder.jpg",
  TwcmTopping: "twcmTopping.jpg",
  ChocolateCurlTopping: "chocolateCurlTopping.jpg",
  CaramelBruleeTopping: "caramelBruleeTopping.jpg",
  RedGreenTopping: "redGreenTopping.jpg",
  Ice: "ice.jpg",
  IcedCup: "icedCup.jpg",
  Shaker: "shaker.jpg",
  ColdWater: "coldWater.jpg",
  Lemonade: "lemonade.jpg"
}